apiVersion: apps/v1
kind: Deployment
metadata:
  name: oktepy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oktepy
  template:
    metadata:
      labels:
        app: oktepy
    spec:
      containers:
      - image: okteto.dev/oktepy:latest
        name: oktepy
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "487fb16c-6fb0-4d9a-8162-a155bd013c9c"
        - name: Vless_Path
          value: "/487fb16c-6fb0-4d9a-8162-a155bd013c9c-vl"
        - name: Vmess_UUID
          value: "487fb16c-6fb0-4d9a-8162-a155bd013c9c"
        - name: Vmess_Path
          value: "/487fb16c-6fb0-4d9a-8162-a155bd013c9c-vm"
        - name: Share_Path
          value: "/v2liwsdfrwrk"
